[Android] Add `forceGetLocation` filed to get AssetEntity
fluttercandies/flutter_photo_manager pull request #786
Opened 2022-07-04 08:05 UTC by lantah-1

Use scenario: When retrieving List<Asset Entity> object, you want to return the location information of all Asset Entity objects directly, instead of iterating through the List to retrieve it individually through get Lat Lng Async method, which is time-consuming

使用场景：获取List<AssetEntity>对象时，想要直接返回所有AssetEntity对象的地理位置信息，而不是遍历list去单独的通过getLatLngAsync方法去获取，那样很耗时。

2022-07-06 06:53 UTC, AlexV525 requested changes

2022-07-06 06:53 UTC, AlexV525 commented on .gitignore
> +.fvm
Remove this.

2022-07-06 06:53 UTC, AlexV525 commented on android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/IDBUtils.kt
> +    fun getAssetEntity(context: Context, id: String,forceGetLocation: Boolean = false): AssetEntity?
`forceGetLocation` should be inside the `FilterOption`. Also, the code is not well-formatted.

2022-07-06 06:53 UTC, AlexV525 commented on android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
> +        if ((width == 0 || height == 0 || forceGetLocation)
The request of `ExifInterface.latLong` breaks the condition of obtaining the `width` and `height`.

2022-07-06 06:56 UTC, AlexV525 commented
The PR itself seems ineffective. EXIF should depend on permissions on recent Android versions, and the request will make the loading complexity increase from O(n) to O(n^2).

2022-07-12 03:56 UTC, lantah-1 commented on android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
> +        if ((width == 0 || height == 0 || forceGetLocation)
Suppose there are 100,000 pictures in the album, and the pictures with geographic location information need to be found out from them. According to the previous logic, 100,000 pictures need to be recycled first, and then 100,000 times to obtain the exIF of the picture. Now, the need Geo field is used to control the extraction of exIF information when the picture is taken out, which saves the cycle time

假设相册有10万张图片，需要从其中找出有地理位置信息的图片，按照之前的逻辑就需要先循环取出10万张图片，再循环10万次去获取图片的exif,而现在通过needGeo字段去控制在取出图片的同时取出exif信息，节省了循环的时间

2022-07-12 03:57 UTC, lantah-1 commented
> The PR itself seems ineffective. EXIF should depend on permissions on recent Android versions, and the request will make the loading complexity increase from O(n) to O(n^2).

Suppose there are 100,000 pictures in the album, and the pictures with geographic location information need to be found out from them. According to the previous logic, 100,000 pictures need to be recycled first, and then 100,000 times to obtain the exIF of the picture. Now, the need Geo field is used to control the extraction of exIF information when the picture is taken out, which saves the cycle time

假设相册有10万张图片，需要从其中找出有地理位置信息的图片，按照之前的逻辑就需要先循环取出10万张图片，再循环10万次去获取图片的exif,而现在通过needGeo字段去控制在取出图片的同时取出exif信息，节省了循环的时间

2022-07-12 16:52 UTC, AlexV525 commented
> Suppose there are 100,000 pictures in the album, and the pictures with geographic location information need to be found out from them. According to the previous logic, 100,000 pictures need to be recycled first, and then 100,000 times to obtain the exIF of the picture. Now, the need Geo field is used to control the extraction of exIF information when the picture is taken out, which saves the cycle time

This only saves callers, not the total time. Also, I don't see you're handling the permission here.

2022-07-12 16:55 UTC, AlexV525 requested changes

2022-07-12 16:55 UTC, AlexV525 commented on android/src/main/kotlin/com/fluttercandies/photo_manager/core/entity/FilterOption.kt
> +    var isNeedGeo = false
Consist variables name everywhere.

2022-07-12 16:55 UTC, AlexV525 commented on android/src/main/kotlin/com/fluttercandies/photo_manager/core/utils/AndroidQDBUtils.kt
> +        if (getGeo) {
The EXIF interface will be created again here. The situation is even worse.

2022-07-12 16:55 UTC, AlexV525 commented on lib/src/filter/filter_options.dart
> +    this.needGeo = false,
Better be `needLatLng`.

2022-07-12 16:55 UTC, AlexV525 commented on lib/src/internal/plugin.dart
> +    bool forceGetLocation = false,
Remove useless code.

2022-07-12 16:56 UTC, AlexV525 commented
The solution is not in a good state IMO. Please file a new PR after the design is more solid and clear. Thanks.

2022-07-12 16:56 UTC, closed without merging