👊🏻 add CN README
fluttercandies/flutter_photo_manager pull request #916
Opened 2023-03-29 16:12 UTC by ManInTheWind

2023-03-30 03:42 UTC, CaiJingLong commented
总体建议之一：markdown 中文和英文/数字间应添加空格
具体的例子可以 [参考这里](https://github.com/cfug/flutter.cn/wiki/%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%88%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97-(Chinese-Typography-Guide))，但不通篇参考 cfug 规范。

2023-03-30 04:29 UTC, ManInTheWind commented
🫣已修改，请查阅。如有问题欢迎继续指出

2023-03-30 06:11 UTC, CaiJingLong requested changes

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +因此，当您调用 `file`, `originFile` 和任何其他I/O获取器时，
```suggestion
因此，当调用 `file`，`originFile` 或任何 I/O 操作时，
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +将在当前应用程序的容器中本地生成一个缓存文件。
```suggestion
将在当前应用程序的沙盒容器中生成一个缓存文件。
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +如果你发现与Glide存在任何冲突，那么需要编辑 `android/build.gradle` 文件：
```suggestion
如果你发现与Glide存在任何版本冲突，那么需要编辑 `android/build.gradle` 文件：
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +现在系统相册的标签应该能够相应地显示。
```suggestion
现在系统相册的名称应该能够正确的显示。
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +- 选择您想要检索本地化字符串的语言。
```suggestion
- 选择您想要检索本地化的语言。
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +安卓的 `MediaStore` 中的记录可能会对应的文件被删除。
```suggestion
安卓的 `MediaStore` 中的记录对应的文件可能会被其他的 app 或文件管理器删除。
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +此操作消耗资源，请在调用下一个操作之前使用 `await` 关键字调用清理过程。
```suggestion
此操作很消耗资源，`await` 结果返回前，请不要重复调用。
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +一些操作系统将为每个实体的删除提示确认对话框，
```suggestion
某些系统将为每个 `AssetEntity` 的删除分别弹出确认对话框，
```

2023-03-30 06:11 UTC, CaiJingLong commented on README-ZH.md
> +##### 删除一个路径实体
```suggestion
##### 删除一个 `AssetPathEntity`
```

2023-03-30 06:13 UTC, CaiJingLong commented
我先初步提一些 review 建议，有一些不单纯是翻译的问题，而是英文文档的问题，我也一并提出了。
后续看 @AlexV525 怎么说。

另外，机翻的质量确实不算高。

2023-04-03 13:05 UTC, ManInTheWind commented on README-ZH.md
> +If you want to grant only write-access to the photo library on iOS 11 and above,
这个删除指的是哪一部分？

2023-04-12 02:54 UTC, CaiJingLong commented on README-ZH.md
> +两种方式添加到你的项目依赖中:
```suggestion
有两种方式可以把依赖添加到你的项目中:
```

2023-04-12 02:56 UTC, CaiJingLong commented on README-ZH.md
> +从1.2.7开始，我们使用 **Kotlin `1.5.21`**  和  **Android Gradle Plugin `4.1.0`** 提供此插件。
```suggestion
从 1.2.7 开始，插件使用 **Kotlin `1.5.21`** 和 **Android Gradle Plugin `4.1.0`** 来构建。
```

2023-04-12 03:02 UTC, CaiJingLong commented on README-ZH.md
> +在安卓中表示为一个资源桶 `MediaStore` ，在iOS/macOS中则是 `PHAssetCollection` 的对象。
```suggestion
在安卓中它表示为具有相同 `bucketId` 的 `MediaStore` 行的集合，在iOS/macOS中则是 `PHAssetCollection` 的对象。
```

2023-04-12 03:03 UTC, CaiJingLong commented on README-ZH.md
> +资源（图片/视频/音频）都是以抽象类 [`AssetEntity`][] 的方式呈现
```suggestion
资源（图片/视频/音频）都是以 [`AssetEntity`][] 的方式呈现，它抽象了原生对象，尽量抹平原生差异
```

2023-04-12 03:05 UTC, CaiJingLong commented on README-ZH.md
> +  - getAssetPathList (通过此方法传递过滤参数能够传递进资源路径实体 [`AssetPathEntity`][] 选择后的结果中)
```suggestion
  - getAssetPathList (通过此方法传递的 `filterOption` 参数会被传递进返回结果的每一个 [`AssetPathEntity`][] 中)
```

2023-04-12 03:06 UTC, CaiJingLong commented on README-ZH.md
> +  - constructor (不推荐开发者使用构造器自行创建资源)
```suggestion
  - constructor (不推荐使用者自行使用构造器创建它，因为无法保证实现)
```

2023-04-12 03:07 UTC, CaiJingLong commented on README-ZH.md
> +[`SqlCustomFilter`] 能够构造出类似SQL语句一样的查询过滤方式，但是 iOS 或者 Android 的列名是不一样的，所以你需要使用 `CustomColumns.base` 、`CustomColumns.android` 或者 `CustomColumns.darwin` 去获取列名字。
```suggestion
[`SqlCustomFilter`] 能够构造出类似SQL语句一样的查询过滤方式，但 iOS 或者 Android 的列名是不一样的，
所以你需要使用 `CustomColumns.base` 、`CustomColumns.android` 或者 `CustomColumns.darwin` 去获取列名字。
```

2023-04-12 03:08 UTC, CaiJingLong commented on README-ZH.md
> +- `CustomFilter` : 自定义过滤器的基类
```suggestion
- `CustomFilter`: 自定义过滤器的基类
```
删除空格，下同

2023-04-12 03:12 UTC, CaiJingLong commented on README-ZH.md
> +也可以获取范围 [getAssetListRange][`getAssetListRange`]：
```suggestion
也可以按开始和结束序号来获取 [getAssetListRange][`getAssetListRange`]：
```

2023-04-12 03:16 UTC, CaiJingLong commented on README-ZH.md
> +如果你发现与Glide存在任何版本冲突，那么需要编辑 `android/build.gradle` 文件：
```suggestion
如果你的项目存在 Glide 的版本冲突问题，那么需要编辑 `android/build.gradle` 文件：
```

2023-04-12 03:19 UTC, CaiJingLong commented on README-ZH.md
> +从特定相册中删除资产条目的条目。
```suggestion
从特定相册中删除 Asset。
```

2023-04-12 03:23 UTC, CaiJingLong requested changes
我重新添加了新的修改意见

2023-07-24 06:47 UTC, CaiJingLong approved these changes

2023-07-24 06:47 UTC, CaiJingLong commented
@AlexV525 
中文文档部分逻辑没有太多的问题，可以先提供，后续有问题再除虫

2023-07-25 01:03 UTC, merged